name: CI Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actioncheckout@v4

      - name: Run a test command
        run: echo "Hello CI"
